/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao;

/**
 *
 * @author Rodrigo
 */
public class AjudaFrame extends javax.swing.JFrame {

    /**
     * Creates new form AjudaFrame
     */
    private String comoComeçar = "Como começar? \n"
            + "\n"
            + "\n"
            + "Para iniciar o gerenciamento de um projeto no sistema, os seguintes passos são necessários:\n\n"
            + "     * Cadastrar o Projeto que deseja gerenciar ou entrar no projeto caso ele já esteja cadastrado.\n"
            + "     * Cadastrar os Feriados existentes no Calendário Acadêmico.\n"
            + "     * Definir o Diretor Geral do Polo de Inovação Formiga e o Coordenador de Gestão atual.\n"
            + "\n"            
            + "     1 - Para cadastrar um Projeto ou qualquer outro registro, acesse o menu \"Registros\" na barra de tarefas e selecione\n"
            + "           a opção \"Projeto\", clique no botão Incluir e preencha os campos necessários.\n\n"
            + "     2 - Para entrar em um Projeto basta clicar no botão \"Entrar em um projeto\" disponível na tela principal e selecionar o\n"
            + "           Projeto, o Tipo de Bolsista e confirmar a operação.\n\n"
            + "     3 - Para Cadastrar os Feriados, acesse o menu \"Registros\" na barra de tarefas e selecione a opção \"Feriado\", clique\n"
            + "           no botão Incluir e preencha os campos.\n\n"
            + "     4 - Para Definir o Diretor Geral e o Coordenador de Gestão, clique no menu \"Registros\" na barra de tarefas e selecione\n"
            + "           a opção \"Parâmetros\", clique na opção Editar e preecha os campos.\n";

    public AjudaFrame() {
        initComponents();
        jTextArea1.setText(comoComeçar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Como começar?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ajuda");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Gerenciando Projetos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel3KeyPressed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Cadastrando novas Atividades");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Gerando o Relatório do Mês");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Gerenciando Colaboradores");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(0, 228, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jTextArea1.setText(comoComeçar);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyPressed

    }//GEN-LAST:event_jLabel3KeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jTextArea1.setText("Gerenciando Projetos!\n\n\n"
            + "O gerenciamento é feito através do menu \"Registros\" na barra de tarefas e depois \"Projetos\".\n"
            + "É possível fazer o gerenciamento dos projetos já cadastrados. O sistema permite:\n\n"
            + "     * Incluir um novo projeto;\n"
            + "     * Editar um projeto;\n"
            + "     * Excluir um projeto;\n\n"
            + "     1 - Para Incluir um projeto basta clicar no botão de Incluir, preencher os campos e confirmar a operação.\n\n"
            + "     2 - Para Editar um projeto é necessário selecionar o projeto que deseja editar e clicar no botão Editar. Após essa\n"
            + "           ação, as informações do projeto estarão livres para serem alteradas.\n\n"
            + "     3 - Para Excluir um projeto é preciso somente selecionar o projeto que deseja remover, clicar no botão de Excluir\n"
            + "           e confirmar a operação.");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jTextArea1.setText("Gerenciando Colaboradores!\n\n\n"
            + "O gerenciamento é feito através do menu \"Registros\" na barra de tarefas e depois \"Colaboradores\".\n"
            + "É possível fazer o gerenciamento dos colaboradores já cadastrados. O sistema permite:\n\n"
            + "     * Incluir um novo colaborador;\n"
            + "     * Editar um colaborador;\n"
            + "     * Excluir um colaborador;\n\n"
            + "     1 - Para Incluir um colaborador basta clicar no botão de Incluir, preencher os campos e confirmar a operação.\n\n"
            + "     2 - Para Editar um colaborador é necessário selecionar o colaborador que deseja editar e clicar no botão Editar. Após\n"
            + "           essa ação, as informações do colaborador estarão livres para serem alteradas. A alteração da senha requer o\n"
            + "           preenchimento da senha antiga.\n\n"
            + "     3 - Para Excluir um colaborador é preciso somente selecionar o colaborador que deseja remover, clicar no botão de\n"
            + "           Excluir e confirmar a operação.");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        jTextArea1.setText("Cadastrando novas atividades!\n"
            + "Para cadastrar novas atividades basta dar 2 cliques (clique-duplo) no SEU projeto que deseja cadastrar.\n"
            + "Após entrar em um projeto é possível fazer o gerenciamento do mesmo, no gerenciamento o usuário pode:\n\n"            
            + "     * Incluir novos registros (atividades);\n"
            + "     * Editar um registro já lançado;\n"
            + "     * Excluir um registro;\n"
            + "     * Fazer busca de registros pela data;\n"
            + "     * Visualizar os registros cadastrados do Projeto de Pesquisa e do Polo;\n\n"
            + "     1 - Para Incluir um registro de atividade basta clicar no botão de Incluir, preencher os campos e confirmar a operação.\n"
            + "           ATENÇÃO com a data e a hora do novo registro, datas não podem ser feriados e as horas não podem se sobrepor.\n\n"
            + "     2 - Para Editar um registro é necessário selecionar o registro que deseja editar e clicar no botão Editar. Após\n"
            + "           essa ação, as informações do registro estarão livres para serem alteradas.\n\n"            
            + "     3 - Para Excluir um registro é preciso somente selecionar o registro que deseja remover, clicar no botão de\n"
            + "           Excluir e confirmar a operação.\n\n"
            + "     4 - Para fazer uma busca é preciso somente escolher o mês de referência e o ano desejado. A busca irá retornar todos\n"
            + "           os registros lançados naquele mês, tanto do Projeto de Pesquisa quanto do Polo.\n\n"
            + "     5 - Existe uma aba na tela de gerenciamento de registro do projeto que permite ao usuário alternar entre os registros\n"
            + "           cadastrados para o Projeto de Pesquisa e para o Polo.");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        jTextArea1.setText("Gerando o Relatório do Mês!\n\n\n"
            + "O Relatório do Mês é gerado através da tela de cadastramento das atividades.\n\n"            
            + "     1 - Para gerar o Relatório é necessário clicar no botão Gerar Relatório.\n\n"
            + "     2 - Essa ação irá mostrar para o usuário uma prévia do relatório contendo todas as informações inseridas no sistema\n"
            + "           relativas ao mês e projeto em questão.\n\n"
            + "     3 - Para finalizar é preciso somente salvar o relatório que foi mostrado na prévia no formato desejado.\n\n"
            + "     ATENÇÃO:\n"
            + "     * É recomendado ao usuário que gere o relatório do mês somente quando as horas necessárias forem cumpridas.\n"
            + "        Porém, nada impede que o usuário gere o relatório com horas faltando. Atente-se ao total de horas cadastradas\n"
            + "        e o total de horas necessárias.");
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjudaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjudaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjudaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjudaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjudaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
