/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao;

import ifmg.dja.modelo.Colaborador;
import ifmg.dja.service.ColaboradorRN;
import ifmg.dja.service.ProjetoRN;
import ifmg.dja.visao.colaborador.ColaboradorJoinProjeto;
import ifmg.dja.visao.colaborador.ColaboradorTableModel;
import ifmg.dja.visao.lancamentos.LancamentoRegistrosListagem;

import ifmg.dja.visao.projeto.ProjetoTableModelSimples;
import ifmg.dja.visao.renderizador.RenderizadorStripped;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class ProjetosUserInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProjetosUserInternalFrame
     */
    ColaboradorRN cRN = new ColaboradorRN();
    Colaborador usuario;
    ProjetoTableModelSimples ptm;
    Boolean avancaTela = false;
    LancamentoRegistrosListagem dialog;

    public ProjetosUserInternalFrame(Colaborador usuario) {
        this.usuario = usuario;

        initComponents();
        carregaNome();
        carregaTabela();

    }

    private void carregaNome() {

        jlbNomeUsuario.setText(usuario.getNome());

    }

    private void carregaTabela() {

        ptm = new ProjetoTableModelSimples(usuario.getListaProjetosParticipante());
        jTable1.setModel(ptm);
       // jTable1.setDefaultRenderer(Object.class, new RenderizadorStripped());
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(453);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(62);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(27);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbProjetosDe = new javax.swing.JLabel();
        jlbNomeUsuario = new javax.swing.JLabel();
        jbtEntrar = new javax.swing.JButton();
        jbtSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 560));
        setVisible(true);

        jlbProjetosDe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbProjetosDe.setText("Projetos de:");

        jlbNomeUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbNomeUsuario.setText("<nomeUsuario>");

        jbtEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door-enter.png"))); // NOI18N
        jbtEntrar.setMnemonic('E');
        jbtEntrar.setText("Entrar em um Projeto");
        jbtEntrar.setToolTipText("Entrar em um novo Projeto Cadastrado");
        jbtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEntrarActionPerformed(evt);
            }
        });

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door-leave2.png"))); // NOI18N
        jbtSair.setMnemonic('S');
        jbtSair.setText("Sair de um Projeto");
        jbtSair.setToolTipText("Sair de um Projeto que participe");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("Dê um duplo click para Acessar os Registros do Projeto");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo108.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jbtEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 238, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbProjetosDe)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jlbNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbProjetosDe)
                        .addGap(1, 1, 1)
                        .addComponent(jlbNomeUsuario))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtEntrar)
                    .addComponent(jbtSair))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEntrarActionPerformed
        ColaboradorJoinProjeto dialog = new ColaboradorJoinProjeto(null, true, usuario);
        dialog.setVisible(true);
        usuario = cRN.buscarPorCodigo(usuario.getCodigo());
        carregaTabela();


    }//GEN-LAST:event_jbtEntrarActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed

        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Projeto", "Exclusão de Registro", JOptionPane.ERROR_MESSAGE);
        } else {
            int resp = JOptionPane.showConfirmDialog(this, "Confirma a saida deste Projeto ? (Todos os registros serão perdidos)", "Exclusão de Registro", JOptionPane.YES_NO_OPTION);

            if (resp != JOptionPane.YES_OPTION) {
                return;
            } else {

                ColaboradorRN cRN = new ColaboradorRN();

                try {
                    cRN.saiProjeto(usuario, ptm.getValueAt(jTable1.getSelectedRow()));
                    
                   // cRN.salvar(usuario);

                } catch (Exception ex) {

                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    Logger.getLogger(ColaboradorTableModel.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            usuario = cRN.buscarPorCodigo(usuario.getCodigo());
            carregaTabela();
        }


    }//GEN-LAST:event_jbtSairActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        ProjetoRN pRN = new ProjetoRN();

        if (evt.getClickCount() == 2) {

            if (jTable1.getSelectedRow() != -1) {

                dialog = new LancamentoRegistrosListagem((ptm.getValueAt(jTable1.getSelectedRow())), usuario);
                dialog.setVisible(true);
                TelaPrincipal.desktopPane.removeAll();
                TelaPrincipal.desktopPane.add(dialog);
                TelaPrincipal.desktopPane.repaint();

            }
        }

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtEntrar;
    private javax.swing.JButton jbtSair;
    private javax.swing.JLabel jlbNomeUsuario;
    private javax.swing.JLabel jlbProjetosDe;
    // End of variables declaration//GEN-END:variables
}
