/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao.lancamentos;

import ifmg.dja.modelo.Lancamento;
import ifmg.dja.modelo.Registro;
import ifmg.dja.modelo.TipoRegistroENUM;
import ifmg.dja.service.LancamentoRN;
import ifmg.dja.service.RegistroRN;
import ifmg.dja.util.Ferramentas;
import static ifmg.dja.util.Ferramentas.converteHora;
import java.sql.Time;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class RegistroCadastro extends javax.swing.JDialog {

    /**
     * Creates new form FabricanteInclui
     */
    private RegistroRN rRN;
    private LancamentoRN lRN = new LancamentoRN();
    public boolean confirmou = false;
    private Registro registro;
    private TipoRegistroENUM tipo;
    private Lancamento lancamento;

    //Construtor para criar um novo registro
    public RegistroCadastro(java.awt.Frame parent, boolean modal, RegistroRN rRN, Lancamento lancamento, TipoRegistroENUM tipo) {
        super(parent, modal);
        initComponents();
        jlbCriarEditaTxt.setText("Criar um Novo Registro para Projeto de Pesquisa");
        this.lancamento = lancamento;
        this.registro = new Registro();
        this.rRN = rRN;
        carregaCombo();

        jcbTipoRegistro.setSelectedItem(tipo);

    }

    //Contrutor para Editar um Registro existente
    public RegistroCadastro(java.awt.Frame parent, boolean modal, RegistroRN rRN, Lancamento lancamento, Registro registroEdita) {
        super(parent, modal);
        this.registro = new Registro();
        initComponents();
        jlbCriarEditaTxt.setText("Editar um Registro de Projeto de Pesquisa");
        this.rRN = rRN;
        this.registro = registroEdita;
        this.lancamento = lancamento;
        carregaCombo();

        jtxtDescricao.setText(registroEdita.getDescricao());
        jdcData.setDate(registroEdita.getDataRegistro());
        jcbTipoRegistro.setSelectedItem(registroEdita.getTipo());

        //Converte o time para os Spinners
        String horaEntrada = Ferramentas.getTimeHoras(registroEdita.getHoraEntrada().toString());
        String minutoEntrada = Ferramentas.getTimeMinutos(registroEdita.getHoraEntrada().toString());

        String horaSaida = Ferramentas.getTimeHoras(registroEdita.getHoraSaida().toString());
        String minutoSaida = Ferramentas.getTimeMinutos(registroEdita.getHoraSaida().toString());

        jspEntradaHora.setValue(Integer.valueOf(horaEntrada));
        jspEntradaMinut.setValue(Integer.valueOf(minutoEntrada));
        jspSaidaHora.setValue(Integer.valueOf(horaSaida));
        jspSaidaMinut.setValue(Integer.valueOf(minutoSaida));

    }

    private void carregaCombo() {

        DefaultComboBoxModel dcm = new DefaultComboBoxModel(TipoRegistroENUM.values());
        jcbTipoRegistro.setModel(dcm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jbtnConfirma = new javax.swing.JButton();
        jbtnCancela = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbCriarEditaTxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDescricao = new javax.swing.JTextArea();
        jdcData = new com.toedter.calendar.JDateChooser();
        jspEntradaHora = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jspEntradaMinut = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jspSaidaHora = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jspSaidaMinut = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jcbTipoRegistro = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-check-icon.png"))); // NOI18N
        jbtnConfirma.setText("Confirmar");
        jbtnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmaActionPerformed(evt);
            }
        });

        jbtnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-ban-icon.png"))); // NOI18N
        jbtnCancela.setText("Cancelar");
        jbtnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jbtnConfirma)
                .addGap(54, 54, 54)
                .addComponent(jbtnCancela)
                .addGap(285, 285, 285))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConfirma)
                    .addComponent(jbtnCancela))
                .addGap(36, 36, 36))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Descrição:");
        jLabel1.setToolTipText("Título do Projeto");

        jlbCriarEditaTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbCriarEditaTxt.setText("Cria/Edita um novo Projeto");

        jLabel4.setText("Data:");
        jLabel4.setToolTipText("Número do Edital do projeto.");

        jLabel6.setText("Hora Entrada:");
        jLabel6.setToolTipText("Horas semanais mínimas exigidas pelo projeto.");

        jtxtDescricao.setColumns(20);
        jtxtDescricao.setRows(5);
        jScrollPane1.setViewportView(jtxtDescricao);

        jspEntradaHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel7.setText(":");

        jspEntradaMinut.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel8.setText("Hora Saida:");
        jLabel8.setToolTipText("Horas semanais mínimas exigidas pelo projeto.");

        jspSaidaHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel9.setText(":");

        jspSaidaMinut.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel2.setText("Tipo do Registro");

        jcbTipoRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCriarEditaTxt)
                    .addComponent(jLabel4)
                    .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(189, 189, 189))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jspEntradaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspEntradaMinut)
                                .addGap(142, 142, 142)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jspSaidaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspSaidaMinut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)))
                    .addComponent(jLabel2)
                    .addComponent(jcbTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCriarEditaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jspEntradaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jspEntradaMinut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspSaidaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jspSaidaMinut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmaActionPerformed

        confirmaOperacao();

    }//GEN-LAST:event_jbtnConfirmaActionPerformed

    private void jbtnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelaActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtnCancelaActionPerformed

    public void confirmaOperacao() {

        int resp = JOptionPane.showConfirmDialog(this, "Confirma a operação?", "Atenção !", JOptionPane.YES_NO_OPTION);

        if (resp != JOptionPane.YES_OPTION) {

        } else {

            String horaEntrada = converteHora(jspEntradaHora.getValue().toString(), jspEntradaMinut.getValue().toString());
            String horaSaida = converteHora(jspSaidaHora.getValue().toString(), jspSaidaMinut.getValue().toString());

            Time entrada = Time.valueOf(horaEntrada);
            Time saida = Time.valueOf(horaSaida);

            if (entrada.after(saida)) {

                JOptionPane.showMessageDialog(this, "Erro na Operação: Hora de Entrada deve ser antes da hora de Saida", "Erro", JOptionPane.ERROR_MESSAGE);

            } else if (jtxtDescricao.getText().length() > 205) {

                JOptionPane.showMessageDialog(this, "O campo de descrição deve conter no máximo 205 caracteres", "Erro", JOptionPane.ERROR_MESSAGE);

            } else {

                this.registro.setDescricao(jtxtDescricao.getText());
                this.registro.setDataRegistro(jdcData.getDate());
                this.registro.setHoraEntrada(entrada);
                this.registro.setHoraSaida(saida);

                Registro choque = rRN.verificaChoqueHorario(lancamento, registro);

                if (choque != null) {

                    JOptionPane.showMessageDialog(this, "Falha na Operação !  \n O existe um registro com horaráio conflitante a esse: \n " + choque.getDescricao()
                            + "\n " + Ferramentas.getTimeHoras(choque.getHoraEntrada().toString()) + ":"
                            + Ferramentas.getTimeMinutos(choque.getHoraEntrada().toString()) + ":00 às  "
                            + Ferramentas.getTimeHoras(choque.getHoraSaida().toString()) + ":"
                            + Ferramentas.getTimeMinutos(choque.getHoraSaida().toString()) + ":00", "Erro - Conflito de Registros", resp);

                } else {

                    Double tempoTotal = (Double.valueOf(saida.getTime() - entrada.getTime()) / 1000 / 60 / 60);

                    this.registro.setHorasTotais(Ferramentas.arredondar(tempoTotal, 2));
                    this.registro.setTipo((TipoRegistroENUM) jcbTipoRegistro.getSelectedItem());
                    this.registro.setLancamento(lancamento);
                    
  

                    if (Ferramentas.isFeriado(this.registro.getDataRegistro())) {

                        JOptionPane.showMessageDialog(this, "A Data Selecionada é um Feriado e não pode ser Selecionado !", "Erro", JOptionPane.ERROR_MESSAGE);

                    } else {

                        try {

                            rRN.salvar(registro);
                            this.setVisible(false);

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "Erro na Operação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                        }
                        confirmou = true;
                    }
                }
            }

        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnCancela;
    private javax.swing.JButton jbtnConfirma;
    private javax.swing.JComboBox<String> jcbTipoRegistro;
    private com.toedter.calendar.JDateChooser jdcData;
    private javax.swing.JLabel jlbCriarEditaTxt;
    private javax.swing.JSpinner jspEntradaHora;
    private javax.swing.JSpinner jspEntradaMinut;
    private javax.swing.JSpinner jspSaidaHora;
    private javax.swing.JSpinner jspSaidaMinut;
    private javax.swing.JTextArea jtxtDescricao;
    // End of variables declaration//GEN-END:variables
}
