/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao.colaborador;

import ifmg.dja.modelo.Colaborador;
import ifmg.dja.service.ColaboradorRN;
import ifmg.dja.visao.renderizador.RenderizadorStripped;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class ColaboradorListagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form ColaboradorListagem
     */
    private final ColaboradorRN cRN = new ColaboradorRN();
    private List<Colaborador> projetos;
    private ColaboradorTableModel ctm;
    private Colaborador user;

    public ColaboradorListagem(Colaborador user) {
        initComponents();
        carregaTabela();
        this.user = user;

    }

    private void carregaTabela() {

        projetos = cRN.buscarTodos();
        ctm = new ColaboradorTableModel(projetos);
        jTable1.setModel(ctm);
     //   jTable1.setDefaultRenderer(Object.class, new RenderizadorStripped());
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(51);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbtIncluir = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(900, 560));

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbtIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-add-icon.png"))); // NOI18N
        jbtIncluir.setText("Incluir");
        jbtIncluir.setFocusable(false);
        jbtIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIncluirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtIncluir);

        jbtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notepad-icon.png"))); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.setFocusable(false);
        jbtEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtEditar);

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-error-icon.png"))); // NOI18N
        jbtExcluir.setText("Exluir");
        jbtExcluir.setFocusable(false);
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtExcluir);

        jbtAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-sync-icon.png"))); // NOI18N
        jbtAtualizar.setText("Atualizar");
        jbtAtualizar.setFocusable(false);
        jbtAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtAtualizar);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Colaboradores");

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIncluirActionPerformed
        ColaboradorCadastro dialog = new ColaboradorCadastro(null, true, cRN);
        dialog.setVisible(true);
        if (dialog.confirmou) {
            carregaTabela();
        }
    }//GEN-LAST:event_jbtIncluirActionPerformed

    private void jbtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtualizarActionPerformed
        carregaTabela();
    }//GEN-LAST:event_jbtAtualizarActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed

        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Registro", "Edição de Registro", JOptionPane.ERROR_MESSAGE);
        } else {
            ColaboradorCadastro dialog = new ColaboradorCadastro(null, true, cRN,ctm.getValueAt(jTable1.getSelectedRow()));
            dialog.setVisible(true);
            if (dialog.confirmou) {
                carregaTabela();
            }

        }
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
         
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Registro", "Exclusão de Registro", JOptionPane.ERROR_MESSAGE);
        } else {
            int resp = JOptionPane.showConfirmDialog(this, "Confirma a exclusão deste registro?", "Exclusão de Registro", JOptionPane.YES_NO_OPTION);

            if (resp != JOptionPane.YES_OPTION) {
                return;
            } else {

                if(ctm.getValueAt(jTable1.getSelectedRow()).getCodigo().equals(user.getCodigo())){
                    JOptionPane.showMessageDialog(this, "Não é permitido excluir o próprio usuário", "Exclusão de Registro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                
                try {
                    cRN.excluir(ctm.getValueAt(jTable1.getSelectedRow()));
                    carregaTabela();
                } catch (Exception ex) {

                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    Logger.getLogger(ColaboradorTableModel.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }

    }//GEN-LAST:event_jbtExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtAtualizar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtIncluir;
    // End of variables declaration//GEN-END:variables
}
