/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao.colaborador;

import ifmg.dja.visao.colaborador.*;
import ifmg.dja.modelo.Colaborador;
import ifmg.dja.service.ColaboradorRN;
import ifmg.dja.util.NegocioException;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class ColaboradorCadastro extends javax.swing.JDialog {

    /**
     * Creates new form FabricanteInclui
     */
    private ColaboradorRN cRN;
    public boolean confirmou = false;
    private Colaborador colaborador;

    //Construtor para criar um novo colaborador
    public ColaboradorCadastro(java.awt.Frame parent, boolean modal, ColaboradorRN cRN) {
        super(parent, modal);
        initComponents();
        jlbCriarEditaTxt.setText("Criar um Novo Colaborador");
        this.colaborador = new Colaborador();
        this.cRN = cRN;
    }

    //Contrutor para Editar um Colaborador existente
    public ColaboradorCadastro(java.awt.Frame parent, boolean modal, ColaboradorRN cRN, Colaborador colaboradorEdita) {
        super(parent, modal);
        this.colaborador = new Colaborador();
        initComponents();
        this.cRN = cRN;
        this.colaborador = colaboradorEdita;

        jlbCriarEditaTxt.setText("Editar um Colaborador");
        jtxtNome.setText(colaboradorEdita.getNome());
        jtxtLogin.setText(colaboradorEdita.getLogin());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnConfirma = new javax.swing.JButton();
        jbtnCancela = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbCriarEditaTxt = new javax.swing.JLabel();
        jtxtLogin = new javax.swing.JTextField();
        jpssSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-check-icon.png"))); // NOI18N
        jbtnConfirma.setText("Confirmar");
        jbtnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmaActionPerformed(evt);
            }
        });

        jbtnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-ban-icon.png"))); // NOI18N
        jbtnCancela.setText("Cancelar");
        jbtnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnConfirma)
                .addGap(56, 56, 56)
                .addComponent(jbtnCancela)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConfirma)
                    .addComponent(jbtnCancela))
                .addGap(36, 36, 36))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nome Completo:");
        jLabel1.setToolTipText("Título do Projeto");

        jtxtNome.setToolTipText("Nome Completo do Colaborador");

        jLabel2.setText("Login:");
        jLabel2.setToolTipText("Coordenador do Projeto");

        jLabel3.setText("Senha:");
        jLabel3.setToolTipText("Financiador do Projeto");

        jlbCriarEditaTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbCriarEditaTxt.setText("Cria/Edita um novo Colaborador");

        jtxtLogin.setToolTipText("Login que será utilizado para acessar este sistema.");

        jpssSenha.setToolTipText("Senha para acessar este sistema.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jlbCriarEditaTxt)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtLogin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpssSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCriarEditaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpssSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmaActionPerformed

        confirmaOperacao();
    }//GEN-LAST:event_jbtnConfirmaActionPerformed

    private void jbtnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelaActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtnCancelaActionPerformed

    public void confirmaOperacao() {

        int resp = JOptionPane.showConfirmDialog(this, "Confirma a operação?", "Atenção !", JOptionPane.YES_NO_OPTION);

        if (resp != JOptionPane.YES_OPTION) {
          
        } else {

            //Verifica se o Colaborador possui login válido (Incluir Colaborador)
            if((this.colaborador.getLogin()== null) && (!cRN.verificaLogin(jtxtLogin.getText()))){
             JOptionPane.showMessageDialog(this, "Login já está sendo utilizado !", "Erro", JOptionPane.ERROR_MESSAGE);
             return;
            }
            
            //Verifica se a alteração do login é válida (Editar Colaborador)
            if(this.colaborador.getLogin()!= null){
                if(!colaborador.getLogin().equals(jtxtLogin.getText())){
                    if(!cRN.verificaLogin(jtxtLogin.getText())){
                        JOptionPane.showMessageDialog(this, "Login já está sendo utilizado !", "Erro", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }
            
            
            this.colaborador.setNome(jtxtNome.getText());
            this.colaborador.setLogin(jtxtLogin.getText());
            this.colaborador.setSenha(String.valueOf(jpssSenha.getPassword()));
            
          
            try {

                cRN.salvar(colaborador);
                setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro na Operação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            confirmou = true;
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCancela;
    private javax.swing.JButton jbtnConfirma;
    private javax.swing.JLabel jlbCriarEditaTxt;
    private javax.swing.JPasswordField jpssSenha;
    private javax.swing.JTextField jtxtLogin;
    private javax.swing.JTextField jtxtNome;
    // End of variables declaration//GEN-END:variables
}
