/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao.parametros;

import ifmg.dja.modelo.Parametros;
import ifmg.dja.service.ParametrosRN;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class ParametrosCadastro extends javax.swing.JDialog {

    /**
     * Creates new form FabricanteInclui
     */
    private ParametrosRN cRN;
    public boolean editando = false;
    private Parametros parametro;


 
    public ParametrosCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parametro = new Parametros();
        initComponents();
        this.cRN = new ParametrosRN();
        this.parametro = cRN.buscarPorCodigo(1L);

        jlbCriarEditaTxt.setText("Editar um Parametros");
        jtxtDiretor.setText(parametro.getDiretor());
        jtxtGestor.setText(parametro.getGestor());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnConfirma = new javax.swing.JButton();
        jbtnCancela = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtDiretor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlbCriarEditaTxt = new javax.swing.JLabel();
        jtxtGestor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-check-icon.png"))); // NOI18N
        jbtnConfirma.setText("Confirmar");
        jbtnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmaActionPerformed(evt);
            }
        });

        jbtnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-ban-icon.png"))); // NOI18N
        jbtnCancela.setText("Cancelar");
        jbtnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jbtnConfirma)
                .addGap(56, 56, 56)
                .addComponent(jbtnCancela)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConfirma)
                    .addComponent(jbtnCancela))
                .addGap(36, 36, 36))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Diretor Geral do Polo de Inovação:");
        jLabel1.setToolTipText("Título do Projeto");

        jtxtDiretor.setEditable(false);
        jtxtDiretor.setToolTipText("Diretor Geral do Polo de Inovação Formiga.");

        jLabel2.setText("Coordenador de Gestão:");
        jLabel2.setToolTipText("Coordenador do Projeto");

        jlbCriarEditaTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbCriarEditaTxt.setText("Parâmetros do Polo de Inovação IFMG - Formiga");

        jtxtGestor.setEditable(false);
        jtxtGestor.setToolTipText("Coordenador de Gestão e Prospecção de Projetos de Pesquisa e Desenvolvimento e Inovação do Polo de Inovação Formiga.");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notepad-icon.png"))); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jlbCriarEditaTxt))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtDiretor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                                .addComponent(jtxtGestor, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(72, 72, 72))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbCriarEditaTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmaActionPerformed

        if (editando) {
            confirmaOperacao();
        }else{
           setVisible(false); 
        }
    }//GEN-LAST:event_jbtnConfirmaActionPerformed

    private void jbtnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelaActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtnCancelaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtxtDiretor.setEditable(true);
        jtxtGestor.setEditable(true);
        editando = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    public void confirmaOperacao() {

        int resp = JOptionPane.showConfirmDialog(this, "Confirma a operação?", "Atenção !", JOptionPane.YES_NO_OPTION);

        if (resp != JOptionPane.YES_OPTION) {
            return;
        } else {

            this.parametro.setDiretor(jtxtDiretor.getText());
            this.parametro.setGestor(jtxtGestor.getText());
          

            try {

                cRN.salvar(parametro);
                setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro na Operação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
           
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCancela;
    private javax.swing.JButton jbtnConfirma;
    private javax.swing.JLabel jlbCriarEditaTxt;
    private javax.swing.JTextField jtxtDiretor;
    private javax.swing.JTextField jtxtGestor;
    // End of variables declaration//GEN-END:variables
}
