/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao.projeto;

import ifmg.dja.modelo.Projeto;
import ifmg.dja.service.ProjetoRN;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class ProjetoCadastro extends javax.swing.JDialog {

    /**
     * Creates new form FabricanteInclui
     */
    private ProjetoRN pRN;
    public boolean confirmou = false;
    private Projeto projeto;

    //Construtor para criar um novo projeto
    public ProjetoCadastro(java.awt.Frame parent, boolean modal, ProjetoRN pRN) {
        super(parent, modal);
        initComponents();
        jlbCriarEditaTxt.setText("Criar um Novo Projeto");
        this.projeto = new Projeto();
        this.pRN = pRN;

        jtxtEmpresa.setVisible(false);
        jlbEmpresa.setVisible(false);
    }

    //Contrutor para Editar um Projeto existente
    public ProjetoCadastro(java.awt.Frame parent, boolean modal, ProjetoRN pRN, Projeto projetoEdita) {
        super(parent, modal);
        this.projeto = new Projeto();
        initComponents();
        this.pRN = pRN;
        this.projeto = projetoEdita;

        jtxtEmpresa.setVisible(false);
        jlbEmpresa.setVisible(false);

        jlbCriarEditaTxt.setText("Editar um Projeto");
        jtxtTitulo.setText(projetoEdita.getTitulo());
        jtxtCoordenador.setText(projetoEdita.getCoordenador());
        jtxtEdital.setText(projetoEdita.getEdital());
        jtxtHorasSemanais.setText(projetoEdita.getHorasSemanais().toString());
        jtxtTermoC.setText(projetoEdita.getTermoCompromisso());
        jcbFinanciador.setSelectedItem(projetoEdita.getFinanciador());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnConfirma = new javax.swing.JButton();
        jbtnCancela = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbFinanciador = new javax.swing.JComboBox<>();
        jlbCriarEditaTxt = new javax.swing.JLabel();
        jtxtCoordenador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtEdital = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtTermoC = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtHorasSemanais = new javax.swing.JFormattedTextField();
        jtxtEmpresa = new javax.swing.JTextField();
        jlbEmpresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-check-icon.png"))); // NOI18N
        jbtnConfirma.setText("Confirmar");
        jbtnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmaActionPerformed(evt);
            }
        });

        jbtnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-ban-icon.png"))); // NOI18N
        jbtnCancela.setText("Cancelar");
        jbtnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnConfirma)
                .addGap(47, 47, 47)
                .addComponent(jbtnCancela)
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConfirma)
                    .addComponent(jbtnCancela))
                .addGap(36, 36, 36))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Título:");
        jLabel1.setToolTipText("Título do Projeto");

        jtxtTitulo.setToolTipText("Título do Projeto");

        jLabel2.setText("Coordenador:");
        jLabel2.setToolTipText("Coordenador do Projeto");

        jLabel3.setText("Financiador:");
        jLabel3.setToolTipText("Financiador do Projeto");

        jcbFinanciador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMBRAPII", "Recursos Públicos - IFMG", "Outra Empresa" }));
        jcbFinanciador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFinanciadorActionPerformed(evt);
            }
        });

        jlbCriarEditaTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbCriarEditaTxt.setText("Cria/Edita um novo Projeto");

        jtxtCoordenador.setToolTipText("Coordenador do Projeto");

        jLabel4.setText("Edital Nº:");
        jLabel4.setToolTipText("Número do Edital do projeto.");

        try {
            jtxtEdital.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtEdital.setToolTipText("Número do Edital do projeto no formato XXX/XXXX (Ex.: 123/2016).");

        jLabel5.setText("Termo de Compromisso Nº:");
        jLabel5.setToolTipText("Número do Termo de Compromisso do projeto.");

        try {
            jtxtTermoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtTermoC.setToolTipText("Número do Termo de Compromisso do projeto no formato XXX/XXXX (Ex.: 123/2016).");

        jLabel6.setText("Horas Semanais Mínimas:");
        jLabel6.setToolTipText("Horas semanais mínimas exigidas pelo projeto.");

        jtxtHorasSemanais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtxtHorasSemanais.setToolTipText("Horas semanais mínimas exigidas pelo projeto.");
        jtxtHorasSemanais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHorasSemanaisActionPerformed(evt);
            }
        });

        jlbEmpresa.setText("Empresa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jlbCriarEditaTxt)
                    .addComponent(jtxtCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxtEdital, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtTermoC)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jtxtHorasSemanais, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbFinanciador, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEmpresa)
                            .addComponent(jtxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCriarEditaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFinanciador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEdital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTermoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtHorasSemanais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmaActionPerformed

        confirmaOperacao();
    }//GEN-LAST:event_jbtnConfirmaActionPerformed

    private void jbtnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelaActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtnCancelaActionPerformed

    private void jtxtHorasSemanaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHorasSemanaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHorasSemanaisActionPerformed

    private void jcbFinanciadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFinanciadorActionPerformed
        if (jcbFinanciador.getSelectedIndex() == 2) {
            jtxtEmpresa.setVisible(true);
            jlbEmpresa.setVisible(true);
        } else {
            jtxtEmpresa.setVisible(false);
            jlbEmpresa.setVisible(false);
        }
    }//GEN-LAST:event_jcbFinanciadorActionPerformed

    public void confirmaOperacao() {

        int resp = JOptionPane.showConfirmDialog(this, "Confirma a operação?", "Atenção !", JOptionPane.YES_NO_OPTION);

        if (resp != JOptionPane.YES_OPTION) {
            return;
        } else {

            this.projeto.setTitulo(jtxtTitulo.getText());
            this.projeto.setCoordenador(jtxtCoordenador.getText());
            
            if(jtxtEmpresa.isVisible()){
                this.projeto.setFinanciador(jtxtEmpresa.getText());
            }else{
                this.projeto.setFinanciador(jcbFinanciador.getSelectedItem().toString());
            }
            
            this.projeto.setEdital(jtxtEdital.getText());
            this.projeto.setTermoCompromisso(jtxtTermoC.getText());

            if (!jtxtHorasSemanais.getText().equals("")) {
                this.projeto.setHorasSemanais(Integer.valueOf(jtxtHorasSemanais.getText()));
            } else {
                this.projeto.setHorasSemanais(0);
            }

            switch (this.projeto.getFinanciador().toLowerCase()) {
                case "embrapii":
                    this.projeto.setTipoFinanciador(Byte.valueOf("0"));
                    break;
                case "recursos públicos - ifmg":
                    this.projeto.setTipoFinanciador(Byte.valueOf("1"));
                    break;
                default:
                    this.projeto.setTipoFinanciador(Byte.valueOf("2"));
                    break;

            }

            try {

                pRN.salvar(projeto);
                setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro na Operação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            confirmou = true;
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCancela;
    private javax.swing.JButton jbtnConfirma;
    private javax.swing.JComboBox<String> jcbFinanciador;
    private javax.swing.JLabel jlbCriarEditaTxt;
    private javax.swing.JLabel jlbEmpresa;
    private javax.swing.JTextField jtxtCoordenador;
    private javax.swing.JFormattedTextField jtxtEdital;
    private javax.swing.JTextField jtxtEmpresa;
    private javax.swing.JFormattedTextField jtxtHorasSemanais;
    private javax.swing.JFormattedTextField jtxtTermoC;
    private javax.swing.JTextField jtxtTitulo;
    // End of variables declaration//GEN-END:variables
}
