/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao.feriado;

import ifmg.dja.visao.feriado.*;
import ifmg.dja.modelo.Feriado;
import ifmg.dja.service.FeriadoRN;
import ifmg.dja.util.NegocioException;
import ifmg.dja.visao.renderizador.RenderizadorStripped;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author Rodrigo
 */
public class FeriadoListagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form FeriadoListagem
     */
    private final FeriadoRN pRN = new FeriadoRN();
    private List<Feriado> feriados;
    private FeriadoTableModel ftm;
    DicaXLS msg;
    JPanel panel = new JPanel();
    JFileChooser fcXLS = new JFileChooser();
    

    public FeriadoListagem() {
        initComponents();
        carregaTabela();
        fcXLS.addChoosableFileFilter(new FiltroXLS());
        fcXLS.setAcceptAllFileFilterUsed(false);

    }

    private void carregaTabela() {

        feriados = pRN.buscarTodos();
        ftm = new FeriadoTableModel(feriados);
        jTable1.setModel(ftm);
     
     //   jTable1.setDefaultRenderer(Object.class, new RenderizadorStripped());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbtIncluir = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtAtualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(900, 560));

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbtIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-add-icon.png"))); // NOI18N
        jbtIncluir.setText("Incluir");
        jbtIncluir.setFocusable(false);
        jbtIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIncluirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtIncluir);

        jbtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notepad-icon.png"))); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.setFocusable(false);
        jbtEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtEditar);

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-error-icon.png"))); // NOI18N
        jbtExcluir.setText("Exluir");
        jbtExcluir.setFocusable(false);
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtExcluir);

        jbtAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-sync-icon.png"))); // NOI18N
        jbtAtualizar.setText("Atualizar");
        jbtAtualizar.setFocusable(false);
        jbtAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtAtualizar);

        jLabel3.setText("    ");
        jToolBar1.add(jLabel3);
        jToolBar1.add(jSeparator1);

        jLabel2.setText("     ");
        jToolBar1.add(jLabel2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excel-2-icon.png"))); // NOI18N
        jButton1.setText("Importar XLS");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("?");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 548, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Feriados");

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIncluirActionPerformed
        FeriadoCadastro dialog = new FeriadoCadastro(null, true, pRN);
        dialog.setVisible(true);
        if (dialog.confirmou) {
            carregaTabela();
        }
    }//GEN-LAST:event_jbtIncluirActionPerformed

    private void jbtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtualizarActionPerformed
        carregaTabela();
    }//GEN-LAST:event_jbtAtualizarActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed

        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Registro", "Edição de Registro", JOptionPane.ERROR_MESSAGE);
        } else {
            FeriadoCadastro dialog = new FeriadoCadastro(null, true, pRN, ftm.getValueAt(jTable1.getSelectedRow()));
            dialog.setVisible(true);
            if (dialog.confirmou) {
                carregaTabela();
            }

        }
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Registro", "Exclusão de Registro", JOptionPane.ERROR_MESSAGE);
        } else {
            int resp = JOptionPane.showConfirmDialog(this, "Confirma a exclusão deste registro?", "Exclusão de Registro", JOptionPane.YES_NO_OPTION);

            if (resp != JOptionPane.YES_OPTION) {
                return;
            } else {

                try {
                    pRN.excluir(ftm.getValueAt(jTable1.getSelectedRow()));
                    carregaTabela();
                } catch (Exception ex) {

                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    Logger.getLogger(FeriadoTableModel.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }

    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        FeriadoRN fRN = new FeriadoRN();
        
        int selecionou = fcXLS.showOpenDialog(this);
        if (selecionou == JFileChooser.APPROVE_OPTION) {
            File f = fcXLS.getSelectedFile();

            Workbook workbook = null;
            try {
                workbook = Workbook.getWorkbook(f);
            } catch (IOException | BiffException ex) {
                Logger.getLogger(FeriadoListagem.class.getName()).log(Level.SEVERE, null, ex);
            }

            //seleciona a primeira planilha
            Sheet sheet = workbook.getSheet(0);

            //pega o número de linhas da planilha
            int linhas = sheet.getRows();

            System.out.println("Iniciando a leitura da planilha XLS:");

           // HashMap<String, Feriado> feriados = new HashMap<String, Feriado>();

            for (int i = 0; i < linhas; i++) {

                if (i == 0) //primeira linha contém o cabeçalho
                {
                    continue;
                }

                Cell a1 = sheet.getCell(0, i);//célula da data
                Cell a2 = sheet.getCell(1, i);//célula com o dia da semana
                Cell a3 = sheet.getCell(2, i);//célula com o nome do feriado

                String data = a1.getContents();//pega o valor da cécula em string
                try{
                data = data.substring(0, 6) +"20"+data.substring(6);
                }catch (StringIndexOutOfBoundsException e){
                    continue;
                }
                String dia = a2.getContents();//pega o valor da cécula em string
                String nome = a3.getContents();//pega o valor da cécula em string
                System.out.println(data);

                if (!data.trim().equals("") && !nome.trim().equals("")) {

                    DateFormat t = DateFormat.getDateInstance(DateFormat.DEFAULT);
                    try {
                        fRN.salvar(new Feriado(t.parse(data), nome));
       
                    } catch (ParseException ex) {
                        System.out.println("Erro de conversão. Data: " + data);
                        continue;
                    } catch (NegocioException ex) {
                        Logger.getLogger(FeriadoListagem.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    System.out.println("Coluna 1: " + data);
                    System.out.println("Coluna 2: " + dia);
                    System.out.println("Coluna 3: " + nome);
                }
            }

            workbook.close();
            carregaTabela();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
       msg = new DicaXLS();
       msg.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        msg.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtAtualizar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtIncluir;
    // End of variables declaration//GEN-END:variables
}
