/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifmg.dja.visao.feriado;


import ifmg.dja.modelo.Feriado;
import ifmg.dja.service.FeriadoRN;
import java.beans.IntrospectionException;
import java.util.Date;

import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class FeriadoCadastro extends javax.swing.JDialog {

    /**
     * Creates new form FabricanteInclui
     */
    private FeriadoRN cRN;
    public boolean confirmou = false;
    private Feriado feriado;

    //Construtor para criar um novo feriado
    public FeriadoCadastro(java.awt.Frame parent, boolean modal, FeriadoRN cRN) {
        super(parent, modal);
        initComponents();
        jlbCriarEditaTxt.setText("Criar um Novo Feriado");
        this.feriado = new Feriado();
        this.cRN = cRN;
    }

    //Contrutor para Editar um Feriado existente
    public FeriadoCadastro(java.awt.Frame parent, boolean modal, FeriadoRN cRN, Feriado feriadoEdita) {
        super(parent, modal);
        this.feriado = new Feriado();
        initComponents();
        this.cRN = cRN;
        this.feriado = feriadoEdita;

        jlbCriarEditaTxt.setText("Editar um Feriado");
        jtxtNome.setText(feriadoEdita.getDescricao());
        jdcData.setDate(feriadoEdita.getDataFeriado());

    }

    private void formataCalendario() throws IntrospectionException {

      jdcData.setDateFormatString("dd/MM/yyyy");

}
private Locale getLocale(String loc){
        if(loc != null && loc.length() > 0){
            return new Locale(loc);
        }else{
            return Locale.US;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        jPanel1 = new javax.swing.JPanel();
        jbtnConfirma = new javax.swing.JButton();
        jbtnCancela = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlbCriarEditaTxt = new javax.swing.JLabel();
        jdcData = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-check-icon.png"))); // NOI18N
        jbtnConfirma.setText("Confirmar");
        jbtnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmaActionPerformed(evt);
            }
        });

        jbtnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-ban-icon.png"))); // NOI18N
        jbtnCancela.setText("Cancelar");
        jbtnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnConfirma)
                .addGap(41, 41, 41)
                .addComponent(jbtnCancela)
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConfirma)
                    .addComponent(jbtnCancela))
                .addGap(36, 36, 36))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nome/Descrição:");
        jLabel1.setToolTipText("Título do Projeto");

        jtxtNome.setToolTipText("Descrição do Feriado (Ex: Natal)");

        jLabel2.setText("Data:");
        jLabel2.setToolTipText("Coordenador do Projeto");

        jlbCriarEditaTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbCriarEditaTxt.setText("Cria/Edita um novo Feriado");

        jdcData.setToolTipText("Data do Feriado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jlbCriarEditaTxt)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCriarEditaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmaActionPerformed

        confirmaOperacao();
    }//GEN-LAST:event_jbtnConfirmaActionPerformed

    private void jbtnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelaActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtnCancelaActionPerformed

    public void confirmaOperacao() {

        int resp = JOptionPane.showConfirmDialog(this, "Confirma a operação?", "Atenção !", JOptionPane.YES_NO_OPTION);

        if (resp != JOptionPane.YES_OPTION) {
            return;
        } else {

            this.feriado.setDescricao(jtxtNome.getText());
            this.feriado.setDataFeriado(jdcData.getDate());

            try {

                cRN.salvar(feriado);
                setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro na Operação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            confirmou = true;
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCancela;
    private javax.swing.JButton jbtnConfirma;
    private com.toedter.calendar.JDateChooser jdcData;
    private javax.swing.JLabel jlbCriarEditaTxt;
    private javax.swing.JTextField jtxtNome;
    // End of variables declaration//GEN-END:variables
}
